<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scenario" nsURI="http://www.inira.fr/scenario" nsPrefix="scenario">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refList" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" lowerBound="1"
        eType="#//Fragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startStep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepList" upperBound="-1"
        eType="#//ExecutionStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventList" upperBound="-1"
        eType="#//EventState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//Future"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mse" lowerBound="1" eType="ecore:EClass platform:/plugin/fr.inria.aoste.timesquare.ecl.feedback.model/model/feedback.ecore#//ModelSpecificEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Future">
    <eLiterals name="tick"/>
    <eLiterals name="noTick" value="1"/>
  </eClassifiers>
</ecore:EPackage>
