/*
 * generated by Xtext
 */
package org.gemoc.gexpressions.xtext;

import org.eclipse.xtext.linking.ILinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GExpressionsRuntimeModule extends org.gemoc.gexpressions.xtext.AbstractGExpressionsRuntimeModule {
	@Override
	public Class<? extends ILinker> bindILinker() {
		return GExpressionsLinker.class;
	}
}
