/*
 * generated by Xtext
 */
package org.gemoc.mocc.cometafsm.model.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FSMDslUiModule extends org.gemoc.mocc.cometafsm.model.xtext.ui.AbstractFSMDslUiModule {
	public FSMDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
