/*
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.gemoc.mocc.ccslmocc.model.xtext.ui.internal.MoCDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MoCDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MoCDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MoCDslActivator.getInstance().getInjector(MoCDslActivator.ORG_GEMOC_MOCC_CCSLMOCC_MODEL_XTEXT_MOCDSL);
	}
	
}
