/*
 * generated by Xtext
 */
package fr.inria.aoste.timesquare.backend;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class EmfExecutionConfigurationRuntimeModule extends
        fr.inria.aoste.timesquare.backend.AbstractEmfExecutionConfigurationRuntimeModule {

}
