/*
* generated by Xtext
*/
package org.gemoc.mocc.ccslmocc.model.xtext.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class MoCDslJavaValidator extends org.gemoc.mocc.ccslmocc.model.xtext.validation.AbstractMoCDslJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
