<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emfExecutionConfiguration" nsURI="http://www.inria.fr/aoste/timesquare/backend/EmfExecutionConfiguration"
    nsPrefix="emfExecutionConfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="EMFExecutionConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forcedClockMappings" upperBound="-1"
        eType="#//ForcedClockMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForcedClockMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clock" eType="ecore:EClass platform:/plugin/fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//Clock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clockToAvoidWhenTrue" eType="ecore:EClass platform:/plugin/fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//Clock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JarImportStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToJar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
