/*
 * generated by Xtext
 */
package org.gemoc.mocc.model.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.gemoc.mocc.model.xtext.ui.internal.MoCLibActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MoCLibExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MoCLibActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MoCLibActivator.getInstance().getInjector(MoCLibActivator.ORG_GEMOC_MOCC_MODEL_XTEXT_MOCLIB);
	}
	
}
