/*
 * generated by Xtext
 */
package org.eclipse.gemoc.gexpressions.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GExpressionsUiModule extends org.eclipse.gemoc.gexpressions.xtext.ui.AbstractGExpressionsUiModule {
	public GExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
