<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gee_configuration" nsURI="http://www.gemoc.org/gee_configuration"
    nsPrefix="gee_configuration">
  <eClassifiers xsi:type="ecore:EClass" name="GemocConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsaModels" lowerBound="1"
        upperBound="-1" eType="#//DSAModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moccModels" lowerBound="1"
        upperBound="-1" eType="#//MoccModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dseModels" lowerBound="1"
        upperBound="-1" eType="#//DSEModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainSpecificMetamodels"
        lowerBound="1" upperBound="-1" eType="#//DomainSpecificMetamodel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//DomainSpecificEditor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSAModel" eSuperTypes="#//LocalResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoccModel" eSuperTypes="#//LocalResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSEModel" eSuperTypes="#//LocalResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapped_mocc" lowerBound="1"
        eType="#//MoccModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapped_dsa" lowerBound="1"
        eType="#//DSAModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificMetamodel" eSuperTypes="#//LocalResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//DomainSpecificEditor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificEditor" eSuperTypes="#//LocalResource"/>
</ecore:EPackage>
