/*
* generated by Xtext
*/
package org.gemoc.mocc.fsmkernel.model.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FSMDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.gemoc.mocc.fsmkernel.model.xtext.ui.internal.FSMDslActivator.getInstance().getInjector("org.gemoc.mocc.fsmkernel.model.xtext.FSMDsl");
	}
	
}
