/*
 * generated by Xtext
 */
package fr.inria.aoste.timesquare.backend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EmfExecutionConfigurationUiModule extends
        fr.inria.aoste.timesquare.backend.ui.AbstractEmfExecutionConfigurationUiModule {
    public EmfExecutionConfigurationUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
