/*
* generated by Xtext
*/
package org.gemoc.mocc.ccslmocc.model.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MoCDslStandaloneSetup extends MoCDslStandaloneSetupGenerated{

	public static void doSetup() {
		new MoCDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

