<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="process" nsURI="http://www.obeo.fr/dsl/process" nsPrefix="process">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An human readable name for this {@link Process}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//Task"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//ProcessVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Reachable DeadEnd PrecedingTasksAtSameLevel FollowingTasksAtSameLevel PreconditionTasksArePreceding"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A task represent a function to be performed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An human readable name for this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An identifier identifying the {@link Task} at its current level (not globally)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An human readable description for this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTask" eType="#//ComposedTask"
        eOpposite="#//ComposedTask/tasks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The {@link ComposedTask} containing this {@link Task} if any, &lt;code>null&lt;/code> otherwise."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precedingTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/followingTasks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Task Tasks} preceding this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="followingTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/precedingTasks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Task Tasks} following this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The precondition allowing this {@link Task} to start. If &lt;code>null&lt;/code> the {@link Task} can be started only if all its {@link fr.obeo.dsl.ProcessUtils#getPossibleTasks(Expression) possible tasks} are {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}. {@link Task Tasks} used in the {@link Expression} must be in {@link fr.obeo.dsl.ProcessUtils#getPossibleTasks(Expression) possible tasks}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessVariable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A variable in the Process wich can be produced or consummed by Tasks."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="VariableIsWrittenAtLeastOnce VariableIsObservedAtLeastOnce"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedTask" eSuperTypes="#//Task">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PathExistance InitialTasksAreContained FinalTasksAreContained DoneTasksAreFinal"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A {@link Task} composed of other {@link Task}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true" eOpposite="#//Task/parentTask">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Task Tasks} composing this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialTasks" lowerBound="1"
        upperBound="-1" eType="#//Task">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initial {@link Task} that can be used as starting point for this {@link ComposedTask}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalTasks" lowerBound="1"
        upperBound="-1" eType="#//Task">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Final {@link Task} that can be used in  {@link ComposedTask#getdoneExpresion() done expression} to mark this {@link ComposedTask} as {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doneExpression" eType="#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An {@link Expression} telling when the {@link ComposedTask} can be considered {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}. {@link Tasks} used in the {@link Expression} must be {@link fr.obeo.dsl.ProcessUtils#getPossibleTasks(Expression) possible tasks}. if &lt;code>null&lt;/code> this {@link ComposedTask} can be considered {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done} only if all its {@link fr.obeo.dsl.ProcessUtils#getPossibleTasks(Expression) possible tasks} are {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionTask" eSuperTypes="#//Task">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ObservedVariableIsReachable"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A {@link Task} performing any action. The {@link ActionTask#getValidation() validation expression} is used to tell when the {@link ActionTask} {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) is done}. Optionally an {@link ActionTask#getAction() action} can be specified to be {@link ActionTask#execute() executed} to meet the {@link ActionTask#getValidation() validation expression}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleExecution" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tells if this {@link ActionTask} can be {@link IProcessRunner#doAction(ProcessContext, ActionTask) done} many times."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenVariables" upperBound="-1"
        eType="#//ProcessVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of {@link ProcessVariable} whose values are modified  by this {@link Task}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observedVariables" upperBound="-1"
        eType="#//ProcessVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of {@link ProcessVariable} that are read by this {@link Task}. If a change occurs on the ProcessVariable the Task is supposed to be interrested  by a notification of this change."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A boolean expression that can be {@link Expression#check() checked}."/>
    </eAnnotations>
    <eOperations name="check" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Checks this {@link Expression}."/>
      </eAnnotations>
      <eParameters name="context" lowerBound="1" eType="#//ProcessContext"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TasksExpression" abstract="true" interface="true"
      eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link Expression} based on {@link Task}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Task Tasks} used to {@link TasksExpression#check() check} this {@link TasksExpression}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllDone" eSuperTypes="#//TasksExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link AllDone#check() Checks} returns &lt;code>true&lt;/code> if all its {@link AllDone#getTasks() tasks} are {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyDone" eSuperTypes="#//TasksExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link AnyDone#check() Checks} returns &lt;code>true&lt;/code> if any of its {@link AnyDone#getTasks() tasks} is {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneDone" eSuperTypes="#//TasksExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link AnyDone#check() Checks} returns &lt;code>true&lt;/code> if one and only one of its {@link AnyDone#getTasks() tasks} is {@link fr.obeo.dsl.process.ProcessUtils#isDone(ProcessContext, Task) done}, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link Not#check() Checks} returns &lt;code>true&lt;/code> if its {@link Not#getExpression() expression} is &lt;code>false&lt;/code>, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Operand."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link And#check() Checks} returns &lt;code>true&lt;/code> if all its {@link And#getExpressions() expressions} are &lt;code>true&lt;/code>, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Operands."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="{@link Or#check() Checks} returns &lt;code>true&lt;/code> if one of its {@link Or#getExpressions() expressions} is &lt;code>true&lt;/code>, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Operands."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An instance of {@link Process}."/>
    </eAnnotations>
    <eOperations name="isDone" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tells if the given {@link ActionTask} is done."/>
      </eAnnotations>
      <eParameters name="task" lowerBound="1" eType="#//ActionTask"/>
    </eOperations>
    <eOperations name="setDone" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Marks the given {@link ActionTask} as done with the given value attached to it."/>
      </eAnnotations>
      <eParameters name="task" lowerBound="1" eType="#//ActionTask"/>
      <eParameters name="value" lowerBound="1" eType="#//Object"/>
    </eOperations>
    <eOperations name="setUndone" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Marks the given {@link ActionTask} as undone with the given reason."/>
      </eAnnotations>
      <eParameters name="task" lowerBound="1" eType="#//ActionTask"/>
      <eParameters name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResult" lowerBound="1" eType="#//Object">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gets the result artifact attached to the given {@link ActionTask} if any, &lt;code>null&lt;/code> otherwise."/>
      </eAnnotations>
      <eParameters name="task" lowerBound="1" eType="#//ActionTask"/>
    </eOperations>
    <eOperations name="setVariableValue" eExceptions="#//IllegalVariableAccessException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="sets the value for the  {@link ProcessVariable} in the current context.&#xD;&#xA;The set will be accepted only if the writter {@link ActionTask} has declared himself as writter for this {@link ProcessVariable}. &#xD;&#xA;If writter is null, the chek is disabled and the set will be done."/>
      </eAnnotations>
      <eParameters name="variable" lowerBound="1" eType="#//ProcessVariable"/>
      <eParameters name="variableValue" lowerBound="1" eType="#//Object"/>
      <eParameters name="writter" eType="#//ActionTask"/>
    </eOperations>
    <eOperations name="getVariableValue" eType="#//Object">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="returns the value for the  {@link ProcessVariable} in the current context."/>
      </eAnnotations>
      <eParameters name="process" lowerBound="1" eType="#//ProcessVariable"/>
    </eOperations>
    <eOperations name="getUndoneReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="task" eType="#//ActionTask"/>
    </eOperations>
    <eOperations name="getProcessVariable" eType="#//ProcessVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="find the  {@link ProcessVariable} with the given name or null if no such variable definition  exists."/>
      </eAnnotations>
      <eParameters name="variableName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variables" changeable="false"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="#//ProcessVariable"/>
        <eTypeArguments eClassifier="#//ContextVariable"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextVariable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An instance of {@link ProcessVariable}."/>
    </eAnnotations>
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableValue" eType="#//Object"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//ProcessVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IllegalVariableAccessException" instanceClassName="fr.obeo.dsl.process.IllegalVariableAccessException"/>
</ecore:EPackage>
