/*
 * generated by Xtext
 */
package org.gemoc.mocc.cometafsm.model.xtext.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class FSMDslScopeProvider extends fr.inria.aoste.timesquare.ccslkernel.library.xtext.scoping.CCSLLibraryScopeProvider {

}
