<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editionextension" nsURI="http://org.gemoc.mocc.fsmmodel/editionextension/1.0"
    nsPrefix="org.gemoc.mocc.fsmmodel.editionextension">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Edition class facilities and syntactic sugar"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerAssignementBlock" eSuperTypes="FSMModel.ecore#//AbstractAction ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="ecore:EClass FSMModel.ecore#//IntegerAssignement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntInfEqual" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/IntegerExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/IntegerExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntSupEqual" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/IntegerExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/IntegerExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealInfEqual" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/RealExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/RealExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealSupEqual" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/RealExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/RealExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntSelfPlusAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryIntegerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntSelfMinusAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryIntegerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntSelfMultiplyAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryIntegerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntSelfDivideAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryIntegerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealSelfPlusAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryRealExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealSelfMinusAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryRealExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealSelfMultiplyAssignement" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClassicalExpression/BinaryRealExpression"/>
</ecore:EPackage>
