/*
* generated by Xtext
*/
package org.gemoc.mocc.model.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.mocc.model.xtext.services.MoCLibGrammarAccess;

public class MoCLibParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MoCLibGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.gemoc.mocc.model.xtext.parser.antlr.internal.InternalMoCLibParser createParser(XtextTokenStream stream) {
		return new org.gemoc.mocc.model.xtext.parser.antlr.internal.InternalMoCLibParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateBaseRelationLibrary";
	}
	
	public MoCLibGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MoCLibGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
