/*
* generated by Xtext
*/
package org.gemoc.mocc.cometaccsl.model.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MoCDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.gemoc.mocc.cometaccsl.model.xtext.ui.internal.MoCDslActivator.getInstance().getInjector("org.gemoc.mocc.cometaccsl.model.xtext.MoCDsl");
	}
	
}
