/**
 * generated by Xtext
 */
package org.gemoc.mocc.cometaccsl.model.xtext.ui.quickfix;

import fr.inria.aoste.timesquare.ccslkernel.library.xtext.ui.quickfix.CCSLLibraryQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class MoCDslQuickfixProvider extends CCSLLibraryQuickfixProvider {
}
