<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moccml" nsURI="http://org.gemoc.moccml/1.0" nsPrefix="moccml">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="StateRelationBasedLibrary" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClockExpressionAndRelation/Library"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineRelationDefinition" eSuperTypes="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClockExpressionAndRelation/ExternalRelationDefinition ../../org.gemoc.mocc.fsmkernel.model/model/FSMModel.ecore#//StateMachineDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinishClock" eSuperTypes="../../org.gemoc.mocc.fsmkernel.model/model/FSMModel.ecore#//AbstractAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clock" lowerBound="1" eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClockExpressionAndRelation/BindableEntity"
        eKeys="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//NamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartClock" eSuperTypes="../../org.gemoc.mocc.fsmkernel.model/model/FSMModel.ecore#//AbstractAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clock" lowerBound="1" eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClockExpressionAndRelation/BindableEntity"
        eKeys="../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//NamedElement/name"/>
  </eClassifiers>
</ecore:EPackage>
