<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tfsmextended" nsURI="http://org.gemoc.sample.tfsm.purek3.model/1.0/extended" nsPrefix="tfsmextended">
  <eClassifiers xsi:type="ecore:EClass" name="TFSM">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//TFSM"/>
    <eOperations name="Init">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="//State">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//State"/>
    <eOperations name="onEnter">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="onLeave">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//Transition"/>
    <eOperations name="fire">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard" abstract="true">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//Guard"/>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalGuard">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//TemporalGuard"/>
    <eSuperTypes href="#//Guard"/>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventGuard">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//EventGuard"/>
    <eSuperTypes href="#//Guard"/>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FSMEvent">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//FSMEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FSMClock">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//FSMClock"/>
    <eOperations name="ticks">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="accept">
      <eAnnotations source="aspect"/>
      <eParameters name="visitor" eType="//IVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTicks" eType="//Integer">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedSystem">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//TimedSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluateGuard">
    <eSuperTypes href="../../org.gemoc.sample.tfsm.purek3.model/model/tfsm.ecore#//EvaluateGuard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IVisitor" instanceClassName="org.gemoc.sample.tfsm.purek3.dsa.IVisitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
</ecore:EPackage>
