/*
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MoCDslUiModule extends org.gemoc.mocc.ccslmocc.model.xtext.ui.AbstractMoCDslUiModule {
	public MoCDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
