/*
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MoCDslRuntimeModule extends org.gemoc.mocc.ccslmocc.model.xtext.AbstractMoCDslRuntimeModule {

}
