<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="glml" nsURI="http://org.gemoc.dse_language.language_level/glml"
    nsPrefix="org.gemoc.dse_language.language_level.glml">
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificEventFile" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageEvents" upperBound="-1"
        eType="#//DomainSpecificEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelEvents" upperBound="-1"
        eType="#//ModelSpecificEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificEvent" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//MocRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainSpecificActions"
        upperBound="-1" eType="#//DomainSpecificAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningDomainSpecificEvent"
        lowerBound="1" eType="#//DomainSpecificEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MocRelation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedCcslRelation" eSuperTypes="#//MocRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//CCSLModel/ClockExpressionAndRelation/Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaSolverRelation" eSuperTypes="#//MocRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSpecificEvent" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reification" eType="#//DomainSpecificEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//MocRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSpecificActions" upperBound="-1"
        eType="#//ModelSpecificAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSpecificAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reification" lowerBound="1"
        eType="#//DomainSpecificAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningModelSpecificEvent"
        lowerBound="1" eType="#//ModelSpecificEvent"/>
  </eClassifiers>
</ecore:EPackage>
