/*
 * generated by Xtext
 */
package org.gemoc.mocc.model.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MoCLibUiModule extends org.gemoc.mocc.model.xtext.ui.AbstractMoCLibUiModule {
	public MoCLibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
