/*
 * generated by Xtext
 */
package org.eclipse.gemoc.gexpressions.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GExpressionsRuntimeModule extends org.eclipse.gemoc.gexpressions.xtext.AbstractGExpressionsRuntimeModule {

}
