/**
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext.scoping;

import org.gemoc.mocc.cometafsm.model.xtext.scoping.FSMDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class MoCDslScopeProvider extends FSMDslScopeProvider {
}
