/*
 * generated by Xtext
 */
package org.gemoc.mocc.model.xtext.scoping;

import fr.inria.aoste.timesquare.ccslkernel.library.xtext.scoping.CCSLLibraryScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class MoCLibScopeProvider extends CCSLLibraryScopeProvider {

}
