/*
* generated by Xtext
*/
package org.gemoc.gel.gexpressions.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GExpressionsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.gemoc.gel.gexpressions.xtext.ui.internal.GExpressionsActivator.getInstance().getInjector("org.gemoc.gel.gexpressions.xtext.GExpressions");
	}
	
}
