/*
* generated by Xtext
*/
package fr.inria.aoste.timesquare.backend.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EmfExecutionConfigurationAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/aoste/timesquare/backend/parser/antlr/internal/InternalEmfExecutionConfiguration.tokens");
	}
}
