<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javasolverinput" nsURI="http://gemoc.org/javasolverinput" nsPrefix="javasolverinput">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaSolverInputFile" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clockDeclarations" upperBound="-1"
        eType="#//usage/Clock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//usage/Constraint" containment="true"/>
  </eClassifiers>
  <eSubpackages name="usage" nsURI="http://gemoc.org/javasolverinput/usage" nsPrefix="usage">
    <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="#//NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Precedes" eSuperTypes="#//usage/Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="clock1" lowerBound="1"
          eType="#//usage/Clock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clock2" lowerBound="1"
          eType="#//usage/Clock"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" eSuperTypes="#//NamedElement"/>
  </eSubpackages>
</ecore:EPackage>
