/*
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext.scoping;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class MoCDslScopeProvider extends org.gemoc.mocc.fsmkernel.model.xtext.scoping.FSMDslScopeProvider {

}
