<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tfsmTrace" nsURI="tfsmTrace" nsPrefix="tfsmTrace">
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_FSMClock_Ticks_Sequence" upperBound="-1" eType="//Steps/Tfsm_FSMClock_Ticks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_FSMEvent_Trigger_Sequence" upperBound="-1" eType="//Steps/Tfsm_FSMEvent_Trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_FSMEvent_UnTrigger_Sequence" upperBound="-1" eType="//Steps/Tfsm_FSMEvent_UnTrigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_State_Visit_Sequence" upperBound="-1" eType="//Steps/Tfsm_State_Visit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_TimeFSM_Init_Sequence" upperBound="-1" eType="//Steps/Tfsm_TimeFSM_Init"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_Transition_Fire_Sequence" upperBound="-1" eType="//Steps/Tfsm_Transition_Fire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tfsm_Transition_Visit_Sequence" upperBound="-1" eType="//Steps/Tfsm_Transition_Visit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1" eType="//States/State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedEvaluateGuards" ordered="false" upperBound="-1" eType="//States/tfsm/TracedEvaluateGuard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedEventGuards" ordered="false" upperBound="-1" eType="//States/tfsm/TracedEventGuard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedFSMClocks" ordered="false" upperBound="-1" eType="//States/tfsm/TracedFSMClock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedFSMEvents" ordered="false" upperBound="-1" eType="//States/tfsm/TracedFSMEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedStates" ordered="false" upperBound="-1" eType="//States/tfsm/TracedState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedTemporalGuards" ordered="false" upperBound="-1" eType="//States/tfsm/TracedTemporalGuard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedTimeFSMs" ordered="false" upperBound="-1" eType="//States/tfsm/TracedTimeFSM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedTimedSystems" ordered="false" upperBound="-1" eType="//States/tfsm/TracedTimedSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfsm_tracedTransitions" ordered="false" upperBound="-1" eType="//States/tfsm/TracedTransition" containment="true"/>
    <eGenericSuperTypes>
      <eTypeArguments>
        <eTypeArguments eClassifier="//Steps/SpecificStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eTypeArguments>
      <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Trace"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="tfsmTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificStep" abstract="true" interface="true">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Step"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="//States/State" eOpposite="//States/State/endedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1" eType="//States/State" eOpposite="//States/State/startedSteps"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_FSMClock_Ticks">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedFSMClock">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedFSMClock) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_FSMEvent_Trigger">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedFSMEvent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedFSMEvent) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_FSMEvent_UnTrigger">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedFSMEvent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedFSMEvent) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_State_Visit">
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedState">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedState) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Tfsm_State_Visit_AbstractSubStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_State_Visit_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_State_Visit_ImplicitStep">
      <eSuperTypes href="#//Steps/Tfsm_State_Visit_AbstractSubStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_TimeFSM_Init">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedTimeFSM">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedTimeFSM) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_Transition_Fire">
      <eSuperTypes href="#//Steps/Tfsm_Transition_Visit_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedTransition">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedTransition) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_Transition_Visit">
      <eOperations name="getCaller" lowerBound="1" eType="//States/tfsm/TracedTransition">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (tfsmTrace.States.tfsm.TracedTransition) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Tfsm_State_Visit_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Tfsm_Transition_Visit_AbstractSubStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_Transition_Visit_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Tfsm_Transition_Visit_ImplicitStep">
      <eSuperTypes href="#//Steps/Tfsm_Transition_Visit_AbstractSubStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="States" nsURI="tfsmTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="FSMClock_numberOfTicks_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTicks" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/tfsm/TracedFSMClock" eOpposite="//States/tfsm/TracedFSMClock/numberOfTicksSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/fSMClock_numberOfTicks_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FSMEvent_isTriggered_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTriggered" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/tfsm/TracedFSMEvent" eOpposite="//States/tfsm/TracedFSMEvent/isTriggeredSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/fSMEvent_isTriggered_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/endingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fSMClock_numberOfTicks_Values" ordered="false" upperBound="-1" eType="//States/FSMClock_numberOfTicks_Value" eOpposite="//States/FSMClock_numberOfTicks_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fSMEvent_isTriggered_Values" ordered="false" upperBound="-1" eType="//States/FSMEvent_isTriggered_Value" eOpposite="//States/FSMEvent_isTriggered_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/startingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeFSM_currentState_Values" ordered="false" upperBound="-1" eType="//States/TimeFSM_currentState_Value" eOpposite="//States/TimeFSM_currentState_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeFSM_lastStateChangeStepNumber_Values" ordered="false" upperBound="-1" eType="//States/TimeFSM_lastStateChangeStepNumber_Value" eOpposite="//States/TimeFSM_lastStateChangeStepNumber_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeFSM_stepNumber_Values" ordered="false" upperBound="-1" eType="//States/TimeFSM_stepNumber_Value" eOpposite="//States/TimeFSM_stepNumber_Value/states"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeFSM_currentState_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" unique="false" eType="//States/tfsm/TracedState">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/tfsm/TracedTimeFSM" eOpposite="//States/tfsm/TracedTimeFSM/currentStateSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/timeFSM_currentState_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeFSM_lastStateChangeStepNumber_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastStateChangeStepNumber" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/tfsm/TracedTimeFSM" eOpposite="//States/tfsm/TracedTimeFSM/lastStateChangeStepNumberSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/timeFSM_lastStateChangeStepNumber_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeFSM_stepNumber_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/tfsm/TracedTimeFSM" eOpposite="//States/tfsm/TracedTimeFSM/stepNumberSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/timeFSM_stepNumber_Values"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepNumber" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State" changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eSubpackages name="tfsm" nsURI="tfsmTrace_tfsm" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedEvaluateGuard" eSuperTypes="//States/tfsm/TracedGuard">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//EvaluateGuard"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedEventGuard" eSuperTypes="//States/tfsm/TracedGuard">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//EventGuard"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedFSMClock" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="numberOfTicksSequence" upperBound="-1" eType="//States/FSMClock_numberOfTicks_Value" containment="true" eOpposite="//States/FSMClock_numberOfTicks_Value/parent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//FSMClock"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedFSMEvent" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="isTriggeredSequence" upperBound="-1" eType="//States/FSMEvent_isTriggered_Value" containment="true" eOpposite="//States/FSMEvent_isTriggered_Value/parent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//FSMEvent"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedGuard" abstract="true" eSuperTypes="//States/tfsm/TracedNamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedNamedElement" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedState" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//State"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedTemporalGuard" eSuperTypes="//States/tfsm/TracedGuard">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//TemporalGuard"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedTimeFSM" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="currentStateSequence" upperBound="-1" eType="//States/TimeFSM_currentState_Value" containment="true" eOpposite="//States/TimeFSM_currentState_Value/parent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="lastStateChangeStepNumberSequence" upperBound="-1" eType="//States/TimeFSM_lastStateChangeStepNumber_Value" containment="true" eOpposite="//States/TimeFSM_lastStateChangeStepNumber_Value/parent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//TimeFSM"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="stepNumberSequence" upperBound="-1" eType="//States/TimeFSM_stepNumber_Value" containment="true" eOpposite="//States/TimeFSM_stepNumber_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedTimedSystem" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//TimedSystem"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedTransition" eSuperTypes="//States/tfsm/TracedNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacytfsm.xstfsm.xstfsm/model/XSTFSM.ecore#//Transition"/>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
