/*
 * generated by Xtext
 */
package org.gemoc.mocc.cometaccsl.model.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMoCDslValidator extends fr.inria.aoste.timesquare.ccslkernel.library.xtext.validation.CCSLLibraryJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.cometa/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.cometamoc/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.ccslmoc/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel.ccslmodel.clockexpressionandrelation"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.cometatime/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.cometastructure/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.cometadatatype/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.ccsl4cometaspecialisation/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.gemoc.mocc.fsmdefinition/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel.classicalexpression"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel.basicTypes"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel.ccslmodel.clockexpressionandrelation.kernelexpression"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.aoste.timemodel.ccslmodel.clockexpressionandrelation.kernelrelation"));
		return result;
	}
}
