/*
* generated by Xtext
*/
package fr.inria.aoste.timesquare.backend.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EmfExecutionConfigurationOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
