/**
 */
package glml.provider;

import glml.util.GlmlAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GlmlItemProviderAdapterFactory extends GlmlAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GlmlItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.DomainSpecificEventFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainSpecificEventFileItemProvider domainSpecificEventFileItemProvider;

	/**
	 * This creates an adapter for a {@link glml.DomainSpecificEventFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainSpecificEventFileAdapter() {
		if (domainSpecificEventFileItemProvider == null) {
			domainSpecificEventFileItemProvider = new DomainSpecificEventFileItemProvider(this);
		}

		return domainSpecificEventFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.ImportStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportStatementItemProvider importStatementItemProvider;

	/**
	 * This creates an adapter for a {@link glml.ImportStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportStatementAdapter() {
		if (importStatementItemProvider == null) {
			importStatementItemProvider = new ImportStatementItemProvider(this);
		}

		return importStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.DomainSpecificEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainSpecificEventItemProvider domainSpecificEventItemProvider;

	/**
	 * This creates an adapter for a {@link glml.DomainSpecificEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainSpecificEventAdapter() {
		if (domainSpecificEventItemProvider == null) {
			domainSpecificEventItemProvider = new DomainSpecificEventItemProvider(this);
		}

		return domainSpecificEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.DomainSpecificAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainSpecificActionItemProvider domainSpecificActionItemProvider;

	/**
	 * This creates an adapter for a {@link glml.DomainSpecificAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainSpecificActionAdapter() {
		if (domainSpecificActionItemProvider == null) {
			domainSpecificActionItemProvider = new DomainSpecificActionItemProvider(this);
		}

		return domainSpecificActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.ExtendedCcslRelation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedCcslRelationItemProvider extendedCcslRelationItemProvider;

	/**
	 * This creates an adapter for a {@link glml.ExtendedCcslRelation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtendedCcslRelationAdapter() {
		if (extendedCcslRelationItemProvider == null) {
			extendedCcslRelationItemProvider = new ExtendedCcslRelationItemProvider(this);
		}

		return extendedCcslRelationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.JavaSolverRelation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaSolverRelationItemProvider javaSolverRelationItemProvider;

	/**
	 * This creates an adapter for a {@link glml.JavaSolverRelation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaSolverRelationAdapter() {
		if (javaSolverRelationItemProvider == null) {
			javaSolverRelationItemProvider = new JavaSolverRelationItemProvider(this);
		}

		return javaSolverRelationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.ModelSpecificEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelSpecificEventItemProvider modelSpecificEventItemProvider;

	/**
	 * This creates an adapter for a {@link glml.ModelSpecificEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelSpecificEventAdapter() {
		if (modelSpecificEventItemProvider == null) {
			modelSpecificEventItemProvider = new ModelSpecificEventItemProvider(this);
		}

		return modelSpecificEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link glml.ModelSpecificAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelSpecificActionItemProvider modelSpecificActionItemProvider;

	/**
	 * This creates an adapter for a {@link glml.ModelSpecificAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelSpecificActionAdapter() {
		if (modelSpecificActionItemProvider == null) {
			modelSpecificActionItemProvider = new ModelSpecificActionItemProvider(this);
		}

		return modelSpecificActionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (domainSpecificEventFileItemProvider != null) domainSpecificEventFileItemProvider.dispose();
		if (importStatementItemProvider != null) importStatementItemProvider.dispose();
		if (domainSpecificEventItemProvider != null) domainSpecificEventItemProvider.dispose();
		if (domainSpecificActionItemProvider != null) domainSpecificActionItemProvider.dispose();
		if (extendedCcslRelationItemProvider != null) extendedCcslRelationItemProvider.dispose();
		if (javaSolverRelationItemProvider != null) javaSolverRelationItemProvider.dispose();
		if (modelSpecificEventItemProvider != null) modelSpecificEventItemProvider.dispose();
		if (modelSpecificActionItemProvider != null) modelSpecificActionItemProvider.dispose();
	}

}
