/*
 * generated by Xtext
 */
package org.gemoc.mocc.cometafsm.model.xtext.ui.contentassist

import org.gemoc.mocc.cometafsm.model.xtext.ui.contentassist.AbstractFSMDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FSMDslProposalProvider extends AbstractFSMDslProposalProvider {
}
