/**
 * generated by Xtext
 */
package org.gemoc.mocc.cometaccsl.model.xtext.ui.contentassist;

import org.gemoc.mocc.cometaccsl.model.xtext.ui.contentassist.AbstractMoCDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MoCDslProposalProvider extends AbstractMoCDslProposalProvider {
}
