/**
 * generated by Xtext
 */
package org.gemoc.mocc.ccslmocc.model.xtext.ui.quickfix;

import org.gemoc.mocc.cometafsm.model.xtext.ui.quickfix.FSMDslQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class MoCDslQuickfixProvider extends FSMDslQuickfixProvider {
}
