<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gfpl" nsURI="http://org.gemoc.feedback_policy_language/gfpl"
    nsPrefix="org.gemoc.feedback_policy_language">
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//FeedbackRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//FeedbackExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TypeOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" lowerBound="1"
        eType="#//NatureOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOfAction">
    <eLiterals name="force"/>
    <eLiterals name="forbid" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NatureOfAction">
    <eLiterals name="action"/>
    <eLiterals name="clock" value="1"/>
  </eClassifiers>
</ecore:EPackage>
