/*
* generated by Xtext
*/
package org.gemoc.mocc.fsmkernel.model.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class FSMDslProposalProvider extends org.gemoc.mocc.fsmkernel.model.xtext.ui.contentassist.AbstractFSMDslProposalProvider {

}
