/*
 * generated by Xtext
 */
package fr.inria.aoste.timesquare.backend.ui.contentassist;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class EmfExecutionConfigurationProposalProvider extends AbstractEmfExecutionConfigurationProposalProvider {

}
