/*
* generated by Xtext
*/
package org.gemoc.mocc.model.xtext.ui.contentassist;

import org.gemoc.mocc.model.xtext.ui.contentassist.AbstractMoCLibProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MoCLibProposalProvider extends AbstractMoCLibProposalProvider {

}
