/*
 * generated by Xtext
 */
package org.gemoc.mocc.cometafsm.model.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FSMDslRuntimeModule extends org.gemoc.mocc.cometafsm.model.xtext.AbstractFSMDslRuntimeModule {

}
