/*
 * generated by Xtext
 */
package org.gemoc.mocc.model.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MoCLibRuntimeModule extends org.gemoc.mocc.model.xtext.AbstractMoCLibRuntimeModule {

}
