<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conf" nsURI="http://www.gemoc.org/gemoc_language_workbench_conf"
    nsPrefix="conf">
  <eClassifiers xsi:type="ecore:EClass" name="LanguageDefinition">
    <eOperations name="getFileExtensions" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Provides a convenient access to all file extensions declared. This includes both the files extensions declared in the genmodel of the DomainModelProject and the ones declared in the editors"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsaProject" eType="#//DSAProject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelProject" lowerBound="1"
        eType="#//DomainModelProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editorProjects" upperBound="-1"
        eType="#//EditorProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moCCProject" eType="#//MoCCProject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="animatorProjects" upperBound="-1"
        eType="#//AnimatorProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dSEProject" eType="#//DSEProject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectKind" lowerBound="1"
        eType="#//ProjectKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSAProject" eSuperTypes="#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeExecutorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="URI of the class that implement the code excutor required by the engine.&#xD;&#xA;If null or empty, a default K3 code executor will be generated and used."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorProject" abstract="true" eSuperTypes="#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModelProject" eSuperTypes="#//ProjectResource">
    <eOperations name="getEcoreURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getGenmodel" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRootEObjectQualifiedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genmodeluri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelLoaderClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoCCProject" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnimatorProject" abstract="true" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSEProject" eSuperTypes="#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qvtoURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="solverClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SiriusEditorProject" eSuperTypes="#//EditorProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="SiriusAnimatorProject" eSuperTypes="#//AnimatorProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="XTextEditorProject" eSuperTypes="#//EditorProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grammarName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProjectKind">
    <eLiterals name="eclipsePlugin"/>
    <eLiterals name="mavenJar" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeEditorProject" eSuperTypes="#//EditorProject"/>
</ecore:EPackage>
