<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conf" nsURI="http://www.gemoc.org/gemoc_language_workbench_conf"
    nsPrefix="conf">
  <eClassifiers xsi:type="ecore:EClass" name="GemocLanguageWorkbenchConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageDefinitions" upperBound="-1"
        eType="#//LanguageDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectKind" lowerBound="1"
        eType="#//ProjectKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSAProject" abstract="true" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kermeta2DSAProject" eSuperTypes="#//DSAProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsaProject" lowerBound="1"
        eType="#//DSAProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelProject" lowerBound="1"
        eType="#//DomainModelProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editorProjects" lowerBound="1"
        upperBound="-1" eType="#//EditorProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moCModelProject" lowerBound="1"
        eType="#//MoCProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="animatorProjects" lowerBound="1"
        upperBound="-1" eType="#//AnimatorProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dSEProject" lowerBound="1"
        eType="#//DSEProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorProject" abstract="true" eSuperTypes="#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModelProject" abstract="true"
      eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoCProject" abstract="true" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="CCSLMoCProject" eSuperTypes="#//MoCProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnimatorProject" abstract="true" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFEcoreProject" eSuperTypes="#//DomainModelProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfGenmodel" lowerBound="1"
        eType="#//EMFGenmodel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODProject" eSuperTypes="#//EditorProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="SiriusAnimatorProject" eSuperTypes="#//AnimatorProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oDProject" lowerBound="1"
        eType="#//ODProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModHelXMoCProject" eSuperTypes="#//MoCProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSEProject" abstract="true" eSuperTypes="#//ProjectResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ECLProject" eSuperTypes="#//DSEProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TreeEditorProject" eSuperTypes="#//EditorProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFGenmodel" eSuperTypes="#//FileResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XTextEditorProject" eSuperTypes="#//EditorProject"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProjectKind">
    <eLiterals name="eclipsePlugin"/>
    <eLiterals name="mavenJar" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K3DSAProject" eSuperTypes="#//DSAProject"/>
</ecore:EPackage>
