<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="geml" nsURI="http://org.gemoc.execution_model_language/geml"
    nsPrefix="org.gemoc.execution_model_language">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelEvent" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageEvent" lowerBound="1"
        eType="ecore:EClass ../../org.gemoc.mapping_language/model/GemocMappingLanguage.ecore#//LanguageEvent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedObjects" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedMethods" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints : ExpressionFromCCSL (TODO)"
        lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
